const fs = require('fs');
const path = require('path');

// Configuration
const POSTS_DIR = path.join(__dirname, '../src/content/posts');
const TOPICS_FILE = path.join(__dirname, '../src/content/topics.json');
const SCHEDULE_DAYS = [1, 3, 5]; // 1=Mon, 3=Wed, 5=Fri

// Helper to get the next valid schedule date
function getNextScheduleDate(lastDate) {
    const nextDate = new Date(lastDate);
    nextDate.setDate(nextDate.getDate() + 1);

    while (!SCHEDULE_DAYS.includes(nextDate.getDay())) {
        nextDate.setDate(nextDate.getDate() + 1);
    }
    return nextDate;
}

// Find the latest post date
function getLastPostDate() {
    const files = fs.readdirSync(POSTS_DIR).filter(f => f.endsWith('.md'));
    let latestDate = new Date();

    files.forEach(file => {
        const content = fs.readFileSync(path.join(POSTS_DIR, file), 'utf8');
        const match = content.match(/date: "(\d{4}-\d{2}-\d{2})"/);
        if (match) {
            const date = new Date(match[1]);
            if (date > latestDate) latestDate = date;
        }
    });

    return latestDate;
}

// Main Scheduler
function generateSchedule() {
    const topics = JSON.parse(fs.readFileSync(TOPICS_FILE, 'utf8'));
    let lastDate = getLastPostDate();

    console.log('📅 Generating Content Schedule (Mon/Wed/Fri)...');
    console.log('------------------------------------------------');

    topics.forEach((topic, index) => {
        const nextDate = getNextScheduleDate(lastDate);
        const dateStr = nextDate.toISOString().split('T')[0];
        const slug = topic.toLowerCase()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-|-$/g, '');

        const filename = `${slug}.md`;
        const filePath = path.join(POSTS_DIR, filename);

        // Check if file already exists to avoid overwriting
        if (!fs.existsSync(filePath)) {
            const template = `---
title: "${topic}"
date: "${dateStr}"
category: "Strategy"
excerpt: "Coming soon: A deep dive into ${topic}."
author: "Ken D."
---

*Draft generated by SmartHustler Scheduler*

## Introduction
[Write introduction here...]

## Key Point 1
[Details...]

## Key Point 2
[Details...]

## Conclusion
[Wrap up...]
`;
            fs.writeFileSync(filePath, template);
            console.log(`✅ Scheduled: [${dateStr}] ${topic}`);
            lastDate = nextDate;
        } else {
            console.log(`⚠️  Skipped (Exists): ${topic}`);
        }
    });

    console.log('------------------------------------------------');
    console.log(`🎉 Schedule complete! ${topics.length} posts drafted in src/content/posts/`);
}

generateSchedule();
