const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');
const { generateBlogImage } = require('./generate_images');

// Load env
dotenv.config({ path: '.env.local' });
if (!process.env.PERPLEXITY_API_KEY) {
    dotenv.config({ path: path.join(__dirname, '../.env') });
}

const PERPLEXITY_API_KEY = process.env.PERPLEXITY_API_KEY;
const API_URL = 'https://api.perplexity.ai/chat/completions';

if (!PERPLEXITY_API_KEY) {
    console.error('❌ Error: PERPLEXITY_API_KEY is not found in .env files.');
    process.exit(1);
}

const targetFile = process.argv[2];

if (!targetFile) {
    console.log('Usage: node scripts/enhance_post.js <filename_or_slug>');
    console.log('Example: node scripts/enhance_post.js ai-side-hustle.md');
    process.exit(1);
}

// Resolve file path
let filePath = path.join(__dirname, '../src/content/posts', targetFile);
if (!targetFile.endsWith('.md')) filePath += '.md';

if (!fs.existsSync(filePath)) {
    console.error(`❌ File not found: ${filePath}`);
    process.exit(1);
}

async function enhancePost() {
    const originalContent = fs.readFileSync(filePath, 'utf8');

    // Extract Frontmatter and Body
    const frontmatterMatch = originalContent.match(/^(---[\s\S]*?---)/);
    let frontmatter = frontmatterMatch ? frontmatterMatch[1] : '';
    const bodyContent = originalContent.replace(/---[\s\S]*?---/, '').trim();

    // 0. Check & Generate Image (If missing)
    if (!frontmatter.includes('image:')) {
        console.log('🖼️  No image found in frontmatter. Generating one...');

        // Extract title for prompt
        const titleMatch = frontmatter.match(/title:\s*["']?([^"'\n]+)["']?/);
        const title = titleMatch ? titleMatch[1] : path.basename(filePath, '.md').replace(/-/g, ' ');
        const slug = path.basename(filePath, '.md');

        if (process.env.OPENAI_API_KEY) {
            try {
                const imgPath = await generateBlogImage(title, slug);
                if (imgPath) {
                    // Inject image line after category or at end of existing frontmatter tags
                    if (frontmatter.includes('category:')) {
                        frontmatter = frontmatter.replace(/(category:.*)/, `$1\nimage: "${imgPath}"`);
                    } else {
                        frontmatter = frontmatter.replace(/---$/, `image: "${imgPath}"\n---`);
                    }
                    console.log('✅ Image injected into frontmatter.');
                }
            } catch (e) {
                console.error('⚠️ Image gen failed:', e.message);
            }
        }
    }

    // MODE 1: Write from Scratch (if body is empty OR it is a skeleton draft)
    const isSkeleton = bodyContent.includes('[Write introduction here...]') ||
        bodyContent.includes('Draft generated by SmartHustler Scheduler') ||
        bodyContent.length < 50;

    if (isSkeleton) {
        console.log(`📝 Detected SKELETON/EMPTY post: "${path.basename(filePath)}"`);
        console.log(`🤖 Starting AI Author Mode (Cost: ~$0.05)...`);

        // Extract title from frontmatter
        const titleMatch = frontmatter.match(/title:\s*["']?([^"'\n]+)["']?/);
        const title = titleMatch ? titleMatch[1] : path.basename(filePath, '.md').replace(/-/g, ' ');

        const prompt = `
        You are an expert marketing journalist for "Smart Hustler Marketing".
        
        Task: Write a high-quality, 1,200+ word blog post based on this title.
        
        Title: "${title}"
        
        Guidelines:
        1. **Tone:** Professional, actionable, "hustle-oriented".
        2. **Structure:** 
           - Catchy Intro.
           - Key Concepts / Strategies.
           - Deep Dive Analysis.
           - Actionable Steps.
           - Conclusion.
        3. **Formatting:** Use Markdown headers (##), bolding, and lists.
        4. **Products:** Naturally mention "Micro Niche Finder" if relevant to market research, or "Freedom Calculator" for financial topics.
        
        Return ONLY the markdown body.
        `;

        try {
            const response = await fetch(API_URL, {
                method: 'POST',
                headers: {
                    'Authorization': `Bearer ${PERPLEXITY_API_KEY}`,
                    'Content-Type': 'application/json',
                    'Accept': 'application/json',
                },
                body: JSON.stringify({
                    model: 'sonar-pro',
                    messages: [
                        { role: 'system', content: 'You are a senior marketing analyst.' },
                        { role: 'user', content: prompt }
                    ],
                    temperature: 0.2
                })
            });

            if (!response.ok) throw new Error(`API Error: ${response.statusText}`);

            const data = await response.json();
            let newBody = data.choices[0].message.content;

            // Clean markdown blocks
            newBody = newBody.replace(/^```markdown\n/, '').replace(/\n```$/, '');

            // Add Sources if available
            const citations = data.citations || [];
            let sourcesFooter = "";
            if (citations.length > 0) {
                sourcesFooter = "\n## Sources\n\n" + citations.map((url, i) => `*   [${i + 1}] ${url}`).join('\n');
            }

            const finalContent = `${frontmatter}\n\n${newBody}\n\n${sourcesFooter}\n\n---\n*This article was assisted by Smart Hustler AI research technologies.*`;

            fs.writeFileSync(filePath, finalContent);
            console.log(`✅ Success! Wrote full article for: ${path.basename(filePath)}`);
            return;

        } catch (e) {
            console.error(`❌ Generation Failed: ${e.message}`);
            return;
        }
    }

    // MODE 2: Add Citations (if body exists but no sources)
    if (originalContent.includes('## Sources') || originalContent.includes('## References')) {
        console.log('⚠️  This post already has content and sources. Skipping.');
        process.exit(0);
    }

    console.log(`🔍 Content exists. switching to "Citation Mode" for: ${path.basename(filePath)}...`);

    const analysisText = bodyContent.substring(0, 6000);
    const citPrompt = `
    I have a blog post. Find authoritative sources (URLs) that verify the claims.
    
    Content: "${analysisText}"
    
    Return ONLY a markdown list:
    * [Source Title](URL)
    `;

    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${PERPLEXITY_API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: 'sonar-pro',
                messages: [{ role: 'user', content: citPrompt }]
            })
        });

        if (!response.ok) throw new Error(`API Error: ${response.statusText}`);

        const data = await response.json();
        let citationsList = data.choices[0].message.content;
        const apiCitations = data.citations || [];

        if (apiCitations.length > 0 && (!citationsList.includes('http'))) {
            citationsList = apiCitations.map((url, i) => `* [Source ${i + 1}](${url})`).join('\n');
        }

        citationsList = citationsList.replace(/^```markdown\n/, '').replace(/\n```$/, '');
        const newContent = `${originalContent}\n\n## Sources\n\n${citationsList}\n`;

        fs.writeFileSync(filePath, newContent);
        console.log(`✅ Added citations to: ${path.basename(filePath)}`);

    } catch (e) {
        console.error(`❌ Failed: ${e.message}`);
    }
}

enhancePost();
